<template>
  <div class="app-container mms-finish-page">
    <div class="surface filter-card" v-show="showSearch">
      <div class="filter-head"><div class="filter-title"><span class="glyph"></span> 筛选条件</div><a class="adv-link" :class="{ 'is-open': showAdvanced }" @click.prevent="showAdvanced = !showAdvanced"><span>{{ showAdvanced ? '收起' : '高级筛选' }}</span><el-icon class="chev"><ArrowDown /></el-icon></a></div>
      <div class="filter-bar">
        <div class="field"><label>完工编号</label><div class="control"><el-input v-model="queryParams.finishNo" placeholder="请输入" clearable @keyup.enter="handleQuery"><template #prefix><el-icon><Search /></el-icon></template></el-input></div></div>
        <div class="field"><label>工单编号</label><div class="control"><el-input v-model="queryParams.workOrderNo" placeholder="请输入" clearable @keyup.enter="handleQuery" /></div></div>
        <div class="field"><label>产品编码</label><div class="control"><el-input v-model="queryParams.productCode" placeholder="请输入" clearable @keyup.enter="handleQuery" /></div></div>
        <div class="field"><label>产品名称</label><div class="control"><el-input v-model="queryParams.productName" placeholder="请输入" clearable @keyup.enter="handleQuery" /></div></div>
        <div class="field" v-show="showAdvanced"><label>状态</label><div class="control is-select"><el-select v-model="queryParams.status" placeholder="全部" clearable @change="handleQuery"><el-option v-for="d in mms_kit_status" :key="d.value" :label="d.label" :value="d.value" /></el-select></div></div>
        <div class="field" v-show="showAdvanced"><label>批次号</label><div class="control"><el-input v-model="queryParams.batchNo" placeholder="请输入" clearable @keyup.enter="handleQuery" /></div></div>
        <div class="field" v-show="showAdvanced"><label>完工人</label><div class="control"><el-input v-model="queryParams.finishBy" placeholder="请输入" clearable @keyup.enter="handleQuery" /></div></div>
        <div class="field" v-show="showAdvanced"><label>创建日期</label><div class="control"><el-date-picker v-model="dateRange" type="daterange" range-separator="-" start-placeholder="开始日期" end-placeholder="结束日期" value-format="YYYY-MM-DD" style="width: 100%" /></div></div>
      </div>
      <div class="filter-actions"><div class="filter-info"><el-icon><Filter /></el-icon> 已选 {{ activeFilterCount }} 个条件，支持回车快速搜索</div><div class="filter-buttons"><el-button icon="RefreshLeft" @click="resetQuery">重置</el-button><el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button></div></div>
    </div>
    <div class="surface">
      <div class="status-tabs"><div class="tabs-track"><button class="status-tab" :class="{ 'is-active': activeStatusTab === 'all' }" @click="handleStatusTabClick('all')"><span class="dot"></span><span>全部</span><span class="count">{{ statusCounts.all || 0 }}</span></button><button v-for="s in statusTabList" :key="s.value" class="status-tab" :class="{ 'is-active': activeStatusTab === s.value }" @click="handleStatusTabClick(s.value)"><span class="dot"></span><span>{{ s.label }}</span><span class="count">{{ statusCounts[s.value] || 0 }}</span></button></div><button class="tip-pill" @click="showStatusHelp = true"><el-icon><WarningFilled /></el-icon><span>业务操作说明</span></button></div>
      <div class="toolbar"><div class="left"><el-button type="primary" plain icon="Plus" @click="handleAdd" v-hasPermi="['mms:finish:add']">新增</el-button><el-button type="success" plain icon="Edit" :disabled="single" @click="handleUpdate" v-hasPermi="['mms:finish:edit']">修改</el-button><el-button type="danger" plain icon="Delete" :disabled="multiple" @click="handleDelete" v-hasPermi="['mms:finish:remove']">删除</el-button><div class="toolbar-divider"></div><el-button type="warning" plain icon="Download" @click="handleExport" v-hasPermi="['mms:finish:export']">导出</el-button></div><div class="right"><right-toolbar v-model:showSearch="showSearch" @queryTable="getList" :columns="columns" storageKey="mms_finish_columns" /></div></div>
      <div class="table-wrap"><el-table ref="tableRef" v-loading="loading" :data="dataList" border @selection-change="handleSelectionChange" @header-dragend="onHeaderDragEnd" class="app-table"><el-table-column type="selection" width="55" align="center" /><el-table-column label="完工编号" prop="finishNo" key="finishNo" :width="colWidth('finishNo', 140)" resizable v-if="columns.finishNo.visible" /><el-table-column label="工单编号" prop="workOrderNo" key="workOrderNo" :width="colWidth('workOrderNo', 140)" resizable v-if="columns.workOrderNo.visible" /><el-table-column label="产品编码" prop="productCode" key="productCode" :width="colWidth('productCode', 130)" resizable v-if="columns.productCode.visible" /><el-table-column label="产品名称" prop="productName" key="productName" :width="colWidth('productName', 200)" resizable show-overflow-tooltip v-if="columns.productName.visible" /><el-table-column label="单位" prop="unit" key="unit" :width="colWidth('unit', 80)" resizable align="center" v-if="columns.unit.visible" /><el-table-column label="完工数量" prop="finishQty" key="finishQty" :width="colWidth('finishQty', 100)" resizable align="center" v-if="columns.finishQty.visible" /><el-table-column label="合格数量" prop="qualifiedQty" key="qualifiedQty" :width="colWidth('qualifiedQty', 100)" resizable align="center" v-if="columns.qualifiedQty.visible" /><el-table-column label="批次号" prop="batchNo" key="batchNo" :width="colWidth('batchNo', 120)" resizable v-if="columns.batchNo.visible" /><el-table-column label="完工人" prop="finishBy" key="finishBy" :width="colWidth('finishBy', 90)" resizable align="center" v-if="columns.finishBy.visible" /><el-table-column label="是否准时" prop="isOnTime" key="isOnTime" :width="colWidth('isOnTime', 90)" resizable align="center" v-if="columns.isOnTime.visible"><template #default="scope"><span class="badge" :class="scope.row.isOnTime === '1' ? 'green' : 'red'"><span class="dot"></span>{{ dictLabel(mms_status, scope.row.isOnTime) }}</span></template></el-table-column><el-table-column label="状态" prop="status" key="status" :width="colWidth('status', 100)" resizable align="center" v-if="columns.status.visible"><template #default="scope"><span class="badge" :class="badgeClass(scope.row.status)"><span class="dot"></span>{{ statusLabel(scope.row.status) }}</span></template></el-table-column><el-table-column label="创建时间" prop="createTime" key="createTime" :width="colWidth('createTime', 160)" resizable align="center" v-if="columns.createTime.visible"><template #default="scope"><span>{{ parseTime(scope.row.createTime) }}</span></template></el-table-column><el-table-column label="操作" width="180" align="center" fixed="right"><template #default="scope"><el-button link type="primary" icon="Edit" @click="handleUpdate(scope.row)" v-hasPermi="['mms:finish:edit']">修改</el-button><el-button link type="danger" icon="Delete" @click="handleDelete(scope.row)" v-hasPermi="['mms:finish:remove']">删除</el-button></template></el-table-column></el-table></div>
      <pagination v-show="total > 0" :total="total" v-model:page="queryParams.pageNum" v-model:limit="queryParams.pageSize" @pagination="getList" />
    </div>
    <el-dialog :title="title" v-model="open" width="700px" append-to-body><el-form ref="formRef" :model="form" :rules="rules" label-width="120px"><el-row :gutter="20"><el-col :span="12"><el-form-item label="完工编号" prop="finishNo"><el-input v-model="form.finishNo" placeholder="自动生成" disabled /></el-form-item></el-col><el-col :span="12"><el-form-item label="工单编号" prop="workOrderNo"><el-input v-model="form.workOrderNo" placeholder="请输入" /></el-form-item></el-col></el-row><el-row :gutter="20"><el-col :span="12"><el-form-item label="产品编码" prop="productCode"><el-input v-model="form.productCode" placeholder="请输入" /></el-form-item></el-col><el-col :span="12"><el-form-item label="产品名称" prop="productName"><el-input v-model="form.productName" placeholder="请输入" /></el-form-item></el-col></el-row><el-row :gutter="20"><el-col :span="8"><el-form-item label="单位" prop="unit"><el-input v-model="form.unit" placeholder="请输入" /></el-form-item></el-col><el-col :span="8"><el-form-item label="完工数量" prop="finishQty"><el-input-number v-model="form.finishQty" :min="0" :precision="2" style="width: 100%" /></el-form-item></el-col><el-col :span="8"><el-form-item label="合格数量" prop="qualifiedQty"><el-input-number v-model="form.qualifiedQty" :min="0" :precision="2" style="width: 100%" /></el-form-item></el-col></el-row><el-row :gutter="20"><el-col :span="12"><el-form-item label="批次号" prop="batchNo"><el-input v-model="form.batchNo" placeholder="请输入" /></el-form-item></el-col><el-col :span="12"><el-form-item label="完工人" prop="finishBy"><el-input v-model="form.finishBy" placeholder="请输入" /></el-form-item></el-col></el-row><el-row :gutter="20"><el-col :span="12"><el-form-item label="是否准时" prop="isOnTime"><el-select v-model="form.isOnTime" placeholder="请选择"><el-option v-for="d in mms_status" :key="d.value" :label="d.label" :value="d.value" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="状态" prop="status"><el-select v-model="form.status" placeholder="请选择"><el-option v-for="d in mms_kit_status" :key="d.value" :label="d.label" :value="d.value" /></el-select></el-form-item></el-col></el-row><el-form-item label="备注" prop="remark"><el-input v-model="form.remark" type="textarea" placeholder="请输入" /></el-form-item></el-form><template #footer><div class="dialog-footer"><el-button type="primary" @click="submitForm">确 定</el-button><el-button @click="cancel">取 消</el-button></div></template></el-dialog>
    <el-dialog v-model="showStatusHelp" title="完工管理业务操作说明" width="820px" append-to-body><div class="status-help-content"><h4>一、完工管理释义</h4><div class="highlight-card highlight-primary"><div class="highlight-card-title">什么是完工管理？</div><div class="highlight-card-body"><strong>完工管理（Finish Receipt）</strong>是生产管控中记录工单完工入库信息的单据。完工管理记录完工数量、合格数量、报废数量等数据，是工单生命周期中"完工"环节的核心数据载体，支持生产进度追踪和成本核算。<br/><br/>完工管理遵循 <strong>MES 完工确认规范</strong>，通过数量校验（合格数量≤完工数量）确保数据准确性，准时完工指标支持生产绩效分析。</div></div><h4>二、重点业务规则</h4><div class="highlight-card highlight-warning"><div class="highlight-card-title">核心规则</div><div class="highlight-card-body"><p>• <strong>完工编号：</strong>系统自动生成，唯一标识每笔完工记录</p><p>• <strong>数量校验：</strong>合格数量不能大于完工数量</p><p>• <strong>准时完工：</strong>记录是否按计划时间完工，用于绩效分析</p><p>• <strong>工单关联：</strong>完工记录需关联生产工单，确保数据可追溯</p></div></div><h4>三、业务操作流程</h4><el-timeline><el-timeline-item type="primary" :hollow="true"><strong>创建完工记录：</strong>点击「新增」创建完工记录，填写工单编号和完工数量</el-timeline-item><el-timeline-item type="warning" :hollow="true"><strong>记录数据：</strong>填写合格数量、报废数量等完工数据</el-timeline-item><el-timeline-item type="success" :hollow="true"><strong>确认入库：</strong>确认完工信息无误后保存，系统同步更新工单完工数量</el-timeline-item></el-timeline></div><template #footer><el-button type="primary" @click="showStatusHelp = false">我知道了</el-button></template></el-dialog>
  </div>
</template>

<script setup name="FinishReceipt">
import { listFinishReceipt, getFinishReceipt, addFinishReceipt, updateFinishReceipt, delFinishReceipt } from "@/api/mms/finish";
import { useColumnResize } from '@/composables/useColumnResize'
import { Search, Filter, RefreshLeft, ArrowDown, WarningFilled, ArrowRight, QuestionFilled } from '@element-plus/icons-vue'

const { proxy } = getCurrentInstance();
const { mms_kit_status, mms_status } = proxy.useDict("mms_kit_status", "mms_status");
const { colWidth, onHeaderDragEnd, tableRef, applySavedWidths } = useColumnResize('mms_finish_index')

const dataList = ref([]); const open = ref(false); const loading = ref(true); const showSearch = ref(true); const showAdvanced = ref(false);
const ids = ref([]); const single = ref(true); const multiple = ref(true); const total = ref(0); const title = ref("");
const dateRange = ref([]); const activeStatusTab = ref("all"); const statusCounts = ref({}); const showStatusHelp = ref(false);

const statusTabList = computed(() => mms_kit_status.value ? mms_kit_status.value.map(d => ({ label: d.label, value: d.value })) : []);
const defaultColumns = { finishNo: { label: '完工编号', visible: true }, workOrderNo: { label: '工单编号', visible: true }, productCode: { label: '产品编码', visible: true }, productName: { label: '产品名称', visible: true }, unit: { label: '单位', visible: true }, finishQty: { label: '完工数量', visible: true }, qualifiedQty: { label: '合格数量', visible: true }, batchNo: { label: '批次号', visible: true }, finishBy: { label: '完工人', visible: true }, isOnTime: { label: '是否准时', visible: true }, status: { label: '状态', visible: true }, createTime: { label: '创建时间', visible: true } }
function loadColumnVisibility() { try { const saved = localStorage.getItem('mms_finish_columns'); if (saved) { const parsed = JSON.parse(saved); const result = {}; Object.keys(defaultColumns).forEach(key => { result[key] = { label: defaultColumns[key].label, visible: parsed[key] !== undefined ? parsed[key] : defaultColumns[key].visible } }); return result } } catch (e) {} return { ...defaultColumns } }
const columns = ref(loadColumnVisibility())
const activeFilterCount = computed(() => { let c = 0; if (queryParams.value.finishNo) c++; if (queryParams.value.workOrderNo) c++; if (queryParams.value.productCode) c++; if (queryParams.value.productName) c++; if (queryParams.value.status) c++; if (queryParams.value.batchNo) c++; if (queryParams.value.finishBy) c++; if (dateRange.value && dateRange.value.length === 2) c++; return c; });

const data = reactive({ form: {}, queryParams: { pageNum: 1, pageSize: 10, finishNo: undefined, workOrderNo: undefined, productCode: undefined, productName: undefined, status: undefined, batchNo: undefined, finishBy: undefined, params: {} }, rules: { finishNo: [{ required: true, message: "请输入完工编号", trigger: "blur" }], workOrderNo: [{ required: true, message: "请输入工单编号", trigger: "blur" }] } });
const { queryParams, form, rules } = toRefs(data);

function getList() { loading.value = true; listFinishReceipt(proxy.addDateRange(queryParams.value, dateRange.value)).then(response => { dataList.value = response.rows; total.value = response.total; loading.value = false; applySavedWidths(); updateStatusCounts(response.rows); }); }
function updateStatusCounts(rows) { const counts = { all: total.value }; if (mms_kit_status.value) { mms_kit_status.value.forEach(d => { counts[d.value] = rows.filter(r => r.status === d.value).length; }); } statusCounts.value = counts; }
function handleQuery() { showAdvanced.value = false; queryParams.value.pageNum = 1; getList(); }
function resetQuery() { queryParams.value.finishNo = undefined; queryParams.value.workOrderNo = undefined; queryParams.value.productCode = undefined; queryParams.value.productName = undefined; queryParams.value.status = undefined; queryParams.value.batchNo = undefined; queryParams.value.finishBy = undefined; dateRange.value = []; queryParams.value.params = {}; activeStatusTab.value = 'all'; handleQuery(); }
function handleStatusTabClick(status) { activeStatusTab.value = status; queryParams.value.status = status === "all" ? undefined : status; handleQuery(); }
function handleSelectionChange(selection) { ids.value = selection.map(item => item.finishId); single.value = selection.length !== 1; multiple.value = !selection.length; }
function reset() { form.value = { finishNo: undefined, workOrderNo: undefined, productCode: undefined, productName: undefined, unit: undefined, finishQty: undefined, qualifiedQty: undefined, batchNo: undefined, finishBy: undefined, isOnTime: undefined, status: undefined, remark: undefined }; proxy.resetForm("formRef"); }
function handleAdd() { reset(); open.value = true; title.value = "新增完工"; }
function handleUpdate(row) { reset(); const id = row.finishId || ids.value[0]; getFinishReceipt(id).then(response => { form.value = response.data; open.value = true; title.value = "修改完工"; }); }
function submitForm() { proxy.$refs["formRef"].validate(valid => { if (valid) { if (form.value.finishId != null) { updateFinishReceipt(form.value).then(() => { proxy.$modal.msgSuccess("修改成功"); open.value = false; getList(); }); } else { addFinishReceipt(form.value).then(() => { proxy.$modal.msgSuccess("新增成功"); open.value = false; getList(); }); } } }); }
function cancel() { open.value = false; reset(); }
function handleDelete(row) { const delIds = row.finishId || ids.value; proxy.$modal.confirm('是否确认删除选中的完工记录？').then(() => delFinishReceipt(delIds)).then(() => { getList(); proxy.$modal.msgSuccess("删除成功"); }).catch(() => {}); }
function handleExport() { proxy.download("mms/finish/export", { ...queryParams.value }, `finish_${new Date().getTime()}.xlsx`); }
function dictLabel(dictRef, value) { if (!dictRef || !dictRef.value) return '-'; const item = dictRef.value.find(d => d.value == value); return item ? item.label : '-'; }
function statusLabel(status) { return dictLabel(mms_kit_status, status); }
function badgeClass(status) { const map = { '0': 'amber', '1': 'green', '2': 'red' }; return map[status] || 'gray'; }

getList();
</script>

<style src="@/composables/mms-list-styles.scss" lang="scss" scoped></style>
<style scoped>
.mms-finish-page{padding-top:10px;--brand-50:#eef2ff;--brand-100:#e0e7ff;--brand-200:#c7d2fe;--brand-500:#6366f1;--brand-600:#4f46e5;--brand-700:#4338ca;--ink-900:#0f172a;--ink-700:#334155;--ink-500:#64748b;--ink-400:#94a3b8;--ink-300:#cbd5e1;--ink-200:#e2e8f0;--ink-100:#f1f5f9;--ink-50:#f8fafc;--amber-50:#fffbeb;--amber-500:#f59e0b;--amber-700:#b45309;--blue-50:#eff6ff;--blue-500:#3b82f6;--blue-700:#1d4ed8;--green-50:#ecfdf5;--green-500:#10b981;--green-700:#047857;--red-50:#fef2f2;--red-500:#ef4444;--red-700:#b91c1c;--r-sm:6px;--r-md:10px;--r-lg:14px;--shadow-card:0 1px 0 rgba(15,23,42,.04),0 1px 2px rgba(15,23,42,.04);--ease-out:cubic-bezier(.16,.84,.44,1);font-feature-settings:"tnum" 1;color:var(--ink-900)}
</style>