<template>
  <div class="app-container mms-demand-page">
    <div class="surface filter-card" v-show="showSearch">
      <div class="filter-head"><div class="filter-title"><span class="glyph"></span> 筛选条件</div><a class="adv-link" :class="{ 'is-open': showAdvanced }" @click.prevent="showAdvanced = !showAdvanced"><span>{{ showAdvanced ? '收起' : '高级筛选' }}</span><el-icon class="chev"><ArrowDown /></el-icon></a></div>
      <div class="filter-bar">
        <div class="field"><label>需求编号</label><div class="control"><el-input v-model="queryParams.demandNo" placeholder="请输入" clearable @keyup.enter="handleQuery"><template #prefix><el-icon><Search /></el-icon></template></el-input></div></div>
        <div class="field"><label>产品编码</label><div class="control"><el-input v-model="queryParams.productCode" placeholder="请输入" clearable @keyup.enter="handleQuery" /></div></div>
        <div class="field"><label>产品名称</label><div class="control"><el-input v-model="queryParams.productName" placeholder="请输入" clearable @keyup.enter="handleQuery" /></div></div>
        <div class="field"><label>类型</label><div class="control is-select"><el-select v-model="queryParams.demandType" placeholder="全部" clearable @change="handleQuery"><el-option v-for="d in mms_demand_type" :key="d.value" :label="d.label" :value="d.value" /></el-select></div></div>
        <div class="field" v-show="showAdvanced"><label>状态</label><div class="control is-select"><el-select v-model="queryParams.status" placeholder="全部" clearable @change="handleQuery"><el-option v-for="d in mms_demand_status" :key="d.value" :label="d.label" :value="d.value" /></el-select></div></div>
        <div class="field" v-show="showAdvanced"><label>优先级</label><div class="control is-select"><el-select v-model="queryParams.priority" placeholder="全部" clearable @change="handleQuery"><el-option v-for="d in mms_priority" :key="d.value" :label="d.label" :value="d.value" /></el-select></div></div>
        <div class="field" v-show="showAdvanced"><label>客户名称</label><div class="control"><el-input v-model="queryParams.customerName" placeholder="请输入" clearable @keyup.enter="handleQuery" /></div></div>
        <div class="field" v-show="showAdvanced"><label>创建日期</label><div class="control"><el-date-picker v-model="dateRange" type="daterange" range-separator="-" start-placeholder="开始日期" end-placeholder="结束日期" value-format="YYYY-MM-DD" style="width: 100%" /></div></div>
      </div>
      <div class="filter-actions"><div class="filter-info"><el-icon><Filter /></el-icon> 已选 {{ activeFilterCount }} 个条件，支持回车快速搜索</div><div class="filter-buttons"><el-button icon="RefreshLeft" @click="resetQuery">重置</el-button><el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button></div></div>
    </div>
    <div class="surface">
      <div class="status-tabs"><div class="tabs-track"><button class="status-tab" :class="{ 'is-active': activeStatusTab === 'all' }" @click="handleStatusTabClick('all')"><span class="dot"></span><span>全部</span><span class="count">{{ statusCounts.all || 0 }}</span></button><button v-for="s in statusTabList" :key="s.value" class="status-tab" :class="{ 'is-active': activeStatusTab === s.value }" @click="handleStatusTabClick(s.value)"><span class="dot"></span><span>{{ s.label }}</span><span class="count">{{ statusCounts[s.value] || 0 }}</span></button></div><button class="tip-pill" @click="showStatusHelp = true"><el-icon><WarningFilled /></el-icon><span>业务操作说明</span></button></div>
      <div class="toolbar"><div class="left"><el-button type="primary" plain icon="Plus" @click="handleAdd" v-hasPermi="['mms:demand:add']">新增</el-button><el-button type="success" plain icon="Edit" :disabled="single" @click="handleUpdate" v-hasPermi="['mms:demand:edit']">修改</el-button><el-button type="danger" plain icon="Delete" :disabled="multiple" @click="handleDelete" v-hasPermi="['mms:demand:remove']">删除</el-button><div class="toolbar-divider"></div><el-button type="warning" plain icon="Download" @click="handleExport" v-hasPermi="['mms:demand:export']">导出</el-button></div><div class="right"><right-toolbar v-model:showSearch="showSearch" @queryTable="getList" :columns="columns" storageKey="mms_demand_columns" /></div></div>
      <div class="table-wrap"><el-table ref="tableRef" v-loading="loading" :data="dataList" border @selection-change="handleSelectionChange" @header-dragend="onHeaderDragEnd" class="app-table"><el-table-column type="selection" width="55" align="center" /><el-table-column label="需求编号" prop="demandNo" key="demandNo" :width="colWidth('demandNo', 140)" resizable v-if="columns.demandNo.visible" /><el-table-column label="类型" prop="demandType" key="demandType" :width="colWidth('demandType', 100)" resizable align="center" v-if="columns.demandType.visible"><template #default="scope"><span class="badge blue"><span class="dot"></span>{{ dictLabel(mms_demand_type, scope.row.demandType) }}</span></template></el-table-column><el-table-column label="产品编码" prop="productCode" key="productCode" :width="colWidth('productCode', 130)" resizable v-if="columns.productCode.visible" /><el-table-column label="产品名称" prop="productName" key="productName" :width="colWidth('productName', 200)" resizable show-overflow-tooltip v-if="columns.productName.visible" /><el-table-column label="需求数量" prop="demandQty" key="demandQty" :width="colWidth('demandQty', 100)" resizable align="center" v-if="columns.demandQty.visible" /><el-table-column label="需求日期" prop="requireDate" key="requireDate" :width="colWidth('requireDate', 120)" resizable align="center" v-if="columns.requireDate.visible" /><el-table-column label="优先级" prop="priority" key="priority" :width="colWidth('priority', 90)" resizable align="center" v-if="columns.priority.visible"><template #default="scope"><span class="badge" :class="priorityBadgeClass(scope.row.priority)"><span class="dot"></span>{{ dictLabel(mms_priority, scope.row.priority) }}</span></template></el-table-column><el-table-column label="客户名称" prop="customerName" key="customerName" :width="colWidth('customerName', 150)" resizable show-overflow-tooltip v-if="columns.customerName.visible" /><el-table-column label="状态" prop="status" key="status" :width="colWidth('status', 100)" resizable align="center" v-if="columns.status.visible"><template #default="scope"><span class="badge" :class="badgeClass(scope.row.status)"><span class="dot"></span>{{ statusLabel(scope.row.status) }}</span></template></el-table-column><el-table-column label="创建时间" prop="createTime" key="createTime" :width="colWidth('createTime', 160)" resizable align="center" v-if="columns.createTime.visible"><template #default="scope"><span>{{ parseTime(scope.row.createTime) }}</span></template></el-table-column><el-table-column label="操作" width="180" align="center" fixed="right"><template #default="scope"><el-button link type="primary" icon="Edit" @click="handleUpdate(scope.row)" v-hasPermi="['mms:demand:edit']">修改</el-button><el-button link type="danger" icon="Delete" @click="handleDelete(scope.row)" v-hasPermi="['mms:demand:remove']">删除</el-button></template></el-table-column></el-table></div>
      <pagination v-show="total > 0" :total="total" v-model:page="queryParams.pageNum" v-model:limit="queryParams.pageSize" @pagination="getList" />
    </div>
    <el-dialog :title="title" v-model="open" width="700px" append-to-body><el-form ref="formRef" :model="form" :rules="rules" label-width="120px"><el-row :gutter="20"><el-col :span="12"><el-form-item label="需求编号" prop="demandNo"><el-input v-model="form.demandNo" placeholder="自动生成" disabled /></el-form-item></el-col><el-col :span="12"><el-form-item label="类型" prop="demandType"><el-select v-model="form.demandType" placeholder="请选择"><el-option v-for="d in mms_demand_type" :key="d.value" :label="d.label" :value="d.value" /></el-select></el-form-item></el-col></el-row><el-row :gutter="20"><el-col :span="12"><el-form-item label="来源单号" prop="sourceOrderNo"><el-input v-model="form.sourceOrderNo" placeholder="请输入" /></el-form-item></el-col><el-col :span="12"><el-form-item label="客户名称" prop="customerName"><el-input v-model="form.customerName" placeholder="请输入" /></el-form-item></el-col></el-row><el-row :gutter="20"><el-col :span="12"><el-form-item label="产品编码" prop="productCode"><el-input v-model="form.productCode" placeholder="请输入" /></el-form-item></el-col><el-col :span="12"><el-form-item label="产品名称" prop="productName"><el-input v-model="form.productName" placeholder="请输入" /></el-form-item></el-col></el-row><el-row :gutter="20"><el-col :span="12"><el-form-item label="规格型号" prop="specModel"><el-input v-model="form.specModel" placeholder="请输入" /></el-form-item></el-col><el-col :span="12"><el-form-item label="单位" prop="unit"><el-input v-model="form.unit" placeholder="请输入" /></el-form-item></el-col></el-row><el-row :gutter="20"><el-col :span="8"><el-form-item label="需求数量" prop="demandQty"><el-input-number v-model="form.demandQty" :min="0" :precision="2" style="width: 100%" /></el-form-item></el-col><el-col :span="8"><el-form-item label="需求日期" prop="requireDate"><el-date-picker v-model="form.requireDate" type="date" value-format="YYYY-MM-DD" placeholder="选择日期" style="width: 100%" /></el-form-item></el-col><el-col :span="8"><el-form-item label="优先级" prop="priority"><el-select v-model="form.priority" placeholder="请选择"><el-option v-for="d in mms_priority" :key="d.value" :label="d.label" :value="d.value" /></el-select></el-form-item></el-col></el-row><el-row :gutter="20"><el-col :span="12"><el-form-item label="状态" prop="status"><el-select v-model="form.status" placeholder="请选择"><el-option v-for="d in mms_demand_status" :key="d.value" :label="d.label" :value="d.value" /></el-select></el-form-item></el-col></el-row><el-form-item label="备注" prop="remark"><el-input v-model="form.remark" type="textarea" placeholder="请输入" /></el-form-item></el-form><template #footer><div class="dialog-footer"><el-button type="primary" @click="submitForm">确 定</el-button><el-button @click="cancel">取 消</el-button></div></template></el-dialog>
    <el-dialog v-model="showStatusHelp" title="生产需求业务操作说明" width="720px" append-to-body><div class="status-help-content"><h4>一、业务说明</h4><el-descriptions :column="1" border><el-descriptions-item label="生产需求">管理生产需求计划，包括产品、数量、交期等信息</el-descriptions-item></el-descriptions><h4>二、重点规则</h4><div class="highlight-card"><p>• <strong>需求类型：</strong>支持销售订单、安全库存、手动等多种来源</p><p>• <strong>优先级：</strong>高、中、低三个等级，影响排产顺序</p><p>• <strong>需求日期：</strong>记录客户要求的交货日期，用于排产参考</p></div></div><template #footer><el-button type="primary" @click="showStatusHelp = false">我知道了</el-button></template></el-dialog>
  </div>
</template>

<script setup name="Demand">
import { listDemand, getDemand, addDemand, updateDemand, delDemand } from "@/api/mms/demand";
import { useColumnResize } from '@/composables/useColumnResize'
import { Search, Filter, RefreshLeft, ArrowDown, WarningFilled, ArrowRight, QuestionFilled } from '@element-plus/icons-vue'

const { proxy } = getCurrentInstance();
const { mms_demand_type, mms_priority, mms_demand_status } = proxy.useDict("mms_demand_type", "mms_priority", "mms_demand_status");
const { colWidth, onHeaderDragEnd, tableRef, applySavedWidths } = useColumnResize('mms_demand_index')

const dataList = ref([]); const open = ref(false); const loading = ref(true); const showSearch = ref(true); const showAdvanced = ref(false);
const ids = ref([]); const single = ref(true); const multiple = ref(true); const total = ref(0); const title = ref("");
const dateRange = ref([]); const activeStatusTab = ref("all"); const statusCounts = ref({}); const showStatusHelp = ref(false);

const statusTabList = computed(() => mms_demand_status.value ? mms_demand_status.value.map(d => ({ label: d.label, value: d.value })) : []);
const defaultColumns = { demandNo: { label: '需求编号', visible: true }, demandType: { label: '类型', visible: true }, productCode: { label: '产品编码', visible: true }, productName: { label: '产品名称', visible: true }, demandQty: { label: '需求数量', visible: true }, requireDate: { label: '需求日期', visible: true }, priority: { label: '优先级', visible: true }, customerName: { label: '客户名称', visible: true }, status: { label: '状态', visible: true }, createTime: { label: '创建时间', visible: true } }
function loadColumnVisibility() { try { const saved = localStorage.getItem('mms_demand_columns'); if (saved) { const parsed = JSON.parse(saved); const result = {}; Object.keys(defaultColumns).forEach(key => { result[key] = { label: defaultColumns[key].label, visible: parsed[key] !== undefined ? parsed[key] : defaultColumns[key].visible } }); return result } } catch (e) {} return { ...defaultColumns } }
const columns = ref(loadColumnVisibility())
const activeFilterCount = computed(() => { let c = 0; if (queryParams.value.demandNo) c++; if (queryParams.value.productCode) c++; if (queryParams.value.productName) c++; if (queryParams.value.demandType) c++; if (queryParams.value.status) c++; if (queryParams.value.priority) c++; if (queryParams.value.customerName) c++; if (dateRange.value && dateRange.value.length === 2) c++; return c; });

const data = reactive({ form: {}, queryParams: { pageNum: 1, pageSize: 10, demandNo: undefined, demandType: undefined, productCode: undefined, productName: undefined, status: undefined, priority: undefined, customerName: undefined, params: {} }, rules: { demandNo: [{ required: true, message: "请输入需求编号", trigger: "blur" }], productCode: [{ required: true, message: "请输入产品编码", trigger: "blur" }] } });
const { queryParams, form, rules } = toRefs(data);

function getList() { loading.value = true; listDemand(proxy.addDateRange(queryParams.value, dateRange.value)).then(response => { dataList.value = response.rows; total.value = response.total; loading.value = false; applySavedWidths(); updateStatusCounts(response.rows); }); }
function updateStatusCounts(rows) { const counts = { all: total.value }; if (mms_demand_status.value) { mms_demand_status.value.forEach(d => { counts[d.value] = rows.filter(r => r.status === d.value).length; }); } statusCounts.value = counts; }
function handleQuery() { showAdvanced.value = false; queryParams.value.pageNum = 1; getList(); }
function resetQuery() { queryParams.value.demandNo = undefined; queryParams.value.demandType = undefined; queryParams.value.productCode = undefined; queryParams.value.productName = undefined; queryParams.value.status = undefined; queryParams.value.priority = undefined; queryParams.value.customerName = undefined; dateRange.value = []; queryParams.value.params = {}; activeStatusTab.value = 'all'; handleQuery(); }
function handleStatusTabClick(status) { activeStatusTab.value = status; queryParams.value.status = status === "all" ? undefined : status; handleQuery(); }
function handleSelectionChange(selection) { ids.value = selection.map(item => item.demandId); single.value = selection.length !== 1; multiple.value = !selection.length; }
function reset() { form.value = { demandNo: undefined, demandType: undefined, sourceOrderNo: undefined, productCode: undefined, productName: undefined, specModel: undefined, unit: undefined, demandQty: undefined, requireDate: undefined, priority: undefined, customerName: undefined, status: undefined, remark: undefined }; proxy.resetForm("formRef"); }
function handleAdd() { reset(); open.value = true; title.value = "新增生产需求"; }
function handleUpdate(row) { reset(); const id = row.demandId || ids.value[0]; getDemand(id).then(response => { form.value = response.data; open.value = true; title.value = "修改生产需求"; }); }
function submitForm() { proxy.$refs["formRef"].validate(valid => { if (valid) { if (form.value.demandId != null) { updateDemand(form.value).then(() => { proxy.$modal.msgSuccess("修改成功"); open.value = false; getList(); }); } else { addDemand(form.value).then(() => { proxy.$modal.msgSuccess("新增成功"); open.value = false; getList(); }); } } }); }
function cancel() { open.value = false; reset(); }
function handleDelete(row) { const delIds = row.demandId || ids.value; proxy.$modal.confirm('是否确认删除选中的生产需求？').then(() => delDemand(delIds)).then(() => { getList(); proxy.$modal.msgSuccess("删除成功"); }).catch(() => {}); }
function handleExport() { proxy.download("mms/demand/export", { ...queryParams.value }, `demand_${new Date().getTime()}.xlsx`); }
function dictLabel(dictRef, value) { if (!dictRef || !dictRef.value) return '-'; const item = dictRef.value.find(d => d.value == value); return item ? item.label : '-'; }
function statusLabel(status) { return dictLabel(mms_demand_status, status); }
function badgeClass(status) { const map = { '0': 'amber', '1': 'blue', '2': 'green', '3': 'gray' }; return map[status] || 'gray'; }
function priorityBadgeClass(priority) { const map = { '0': 'red', '1': 'amber', '2': 'blue' }; return map[priority] || 'gray'; }

getList();
</script>

<style src="@/composables/mms-list-styles.scss" lang="scss" scoped></style>
<style scoped>
.mms-demand-page{padding-top:10px;--brand-50:#eef2ff;--brand-100:#e0e7ff;--brand-200:#c7d2fe;--brand-500:#6366f1;--brand-600:#4f46e5;--brand-700:#4338ca;--ink-900:#0f172a;--ink-700:#334155;--ink-500:#64748b;--ink-400:#94a3b8;--ink-300:#cbd5e1;--ink-200:#e2e8f0;--ink-100:#f1f5f9;--ink-50:#f8fafc;--amber-50:#fffbeb;--amber-500:#f59e0b;--amber-700:#b45309;--blue-50:#eff6ff;--blue-500:#3b82f6;--blue-700:#1d4ed8;--green-50:#ecfdf5;--green-500:#10b981;--green-700:#047857;--red-50:#fef2f2;--red-500:#ef4444;--red-700:#b91c1c;--r-sm:6px;--r-md:10px;--r-lg:14px;--shadow-card:0 1px 0 rgba(15,23,42,.04),0 1px 2px rgba(15,23,42,.04);--ease-out:cubic-bezier(.16,.84,.44,1);font-feature-settings:"tnum" 1;color:var(--ink-900)}
</style>