<template>
  <div class="app-container mms-qc-page">
    <div class="surface filter-card" v-show="showSearch">
      <div class="filter-head"><div class="filter-title"><span class="glyph"></span> 筛选条件</div><a class="adv-link" :class="{ 'is-open': showAdvanced }" @click.prevent="showAdvanced = !showAdvanced"><span>{{ showAdvanced ? '收起' : '高级筛选' }}</span><el-icon class="chev"><ArrowDown /></el-icon></a></div>
      <div class="filter-bar">
        <div class="field"><label>质检编号</label><div class="control"><el-input v-model="queryParams.qcNo" placeholder="请输入" clearable @keyup.enter="handleQuery"><template #prefix><el-icon><Search /></el-icon></template></el-input></div></div>
        <div class="field"><label>工单编号</label><div class="control"><el-input v-model="queryParams.workOrderNo" placeholder="请输入" clearable @keyup.enter="handleQuery" /></div></div>
        <div class="field"><label>工序</label><div class="control"><el-input v-model="queryParams.processName" placeholder="请输入" clearable @keyup.enter="handleQuery" /></div></div>
        <div class="field"><label>类型</label><div class="control is-select"><el-select v-model="queryParams.qcType" placeholder="全部" clearable @change="handleQuery"><el-option v-for="d in mms_qc_type" :key="d.value" :label="d.label" :value="d.value" /></el-select></div></div>
        <div class="field" v-show="showAdvanced"><label>检验结果</label><div class="control is-select"><el-select v-model="queryParams.qcResult" placeholder="全部" clearable @change="handleQuery"><el-option v-for="d in mms_qc_result" :key="d.value" :label="d.label" :value="d.value" /></el-select></div></div>
        <div class="field" v-show="showAdvanced"><label>检验人</label><div class="control"><el-input v-model="queryParams.qcBy" placeholder="请输入" clearable @keyup.enter="handleQuery" /></div></div>
        <div class="field" v-show="showAdvanced"><label>创建日期</label><div class="control"><el-date-picker v-model="dateRange" type="daterange" range-separator="-" start-placeholder="开始日期" end-placeholder="结束日期" value-format="YYYY-MM-DD" style="width: 100%" /></div></div>
      </div>
      <div class="filter-actions"><div class="filter-info"><el-icon><Filter /></el-icon> 已选 {{ activeFilterCount }} 个条件，支持回车快速搜索</div><div class="filter-buttons"><el-button icon="RefreshLeft" @click="resetQuery">重置</el-button><el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button></div></div>
    </div>
    <div class="surface">
      <div class="status-tabs"><div class="tabs-track"><button class="status-tab" :class="{ 'is-active': activeStatusTab === 'all' }" @click="handleStatusTabClick('all')"><span class="dot"></span><span>全部</span><span class="count">{{ statusCounts.all || 0 }}</span></button><button v-for="s in statusTabList" :key="s.value" class="status-tab" :class="[resultTabClass(s.value), { 'is-active': activeStatusTab === s.value }]" @click="handleStatusTabClick(s.value)"><span class="dot"></span><span>{{ s.label }}</span><span class="count">{{ statusCounts[s.value] || 0 }}</span></button></div><button class="tip-pill" @click="showStatusHelp = true"><el-icon><WarningFilled /></el-icon><span>业务操作说明</span></button></div>
      <div class="toolbar"><div class="left"><el-button type="primary" plain icon="Plus" @click="handleAdd" v-hasPermi="['mms:qc:add']">新增</el-button><el-button type="success" plain icon="Edit" :disabled="single" @click="handleUpdate" v-hasPermi="['mms:qc:edit']">修改</el-button><el-button type="danger" plain icon="Delete" :disabled="multiple" @click="handleDelete" v-hasPermi="['mms:qc:remove']">删除</el-button><div class="toolbar-divider"></div><el-button type="warning" plain icon="Download" @click="handleExport" v-hasPermi="['mms:qc:export']">导出</el-button></div><div class="right"><right-toolbar v-model:showSearch="showSearch" @queryTable="getList" :columns="columns" storageKey="mms_qc_columns" /></div></div>
      <div class="table-wrap"><el-table ref="tableRef" v-loading="loading" :data="dataList" border @selection-change="handleSelectionChange" @header-dragend="onHeaderDragEnd" class="app-table"><el-table-column type="selection" width="55" align="center" /><el-table-column label="质检编号" prop="qcNo" key="qcNo" :width="colWidth('qcNo', 140)" resizable v-if="columns.qcNo.visible" /><el-table-column label="工单编号" prop="workOrderNo" key="workOrderNo" :width="colWidth('workOrderNo', 140)" resizable v-if="columns.workOrderNo.visible" /><el-table-column label="工序" prop="processName" key="processName" :width="colWidth('processName', 100)" resizable v-if="columns.processName.visible" /><el-table-column label="类型" prop="qcType" key="qcType" :width="colWidth('qcType', 100)" resizable align="center" v-if="columns.qcType.visible"><template #default="scope"><span class="badge blue"><span class="dot"></span>{{ dictLabel(mms_qc_type, scope.row.qcType) }}</span></template></el-table-column><el-table-column label="检验数量" prop="inspectQty" key="inspectQty" :width="colWidth('inspectQty', 100)" resizable align="center" v-if="columns.inspectQty.visible" /><el-table-column label="不良数" prop="defectQty" key="defectQty" :width="colWidth('defectQty', 80)" resizable align="center" v-if="columns.defectQty.visible"><template #default="scope"><span :style="{ color: scope.row.defectQty > 0 ? '#ef4444' : 'inherit', fontWeight: scope.row.defectQty > 0 ? 600 : 400 }">{{ scope.row.defectQty }}</span></template></el-table-column><el-table-column label="检验结果" prop="qcResult" key="qcResult" :width="colWidth('qcResult', 100)" resizable align="center" v-if="columns.qcResult.visible"><template #default="scope"><span class="badge" :class="resultBadgeClass(scope.row.qcResult)"><span class="dot"></span>{{ dictLabel(mms_qc_result, scope.row.qcResult) }}</span></template></el-table-column><el-table-column label="检验人" prop="qcBy" key="qcBy" :width="colWidth('qcBy', 90)" resizable align="center" v-if="columns.qcBy.visible" /><el-table-column label="创建时间" prop="createTime" key="createTime" :width="colWidth('createTime', 160)" resizable align="center" v-if="columns.createTime.visible"><template #default="scope"><span>{{ parseTime(scope.row.createTime) }}</span></template></el-table-column><el-table-column label="操作" width="180" align="center" fixed="right"><template #default="scope"><el-button link type="primary" icon="Edit" @click="handleUpdate(scope.row)" v-hasPermi="['mms:qc:edit']">修改</el-button><el-button link type="danger" icon="Delete" @click="handleDelete(scope.row)" v-hasPermi="['mms:qc:remove']">删除</el-button></template></el-table-column></el-table></div>
      <pagination v-show="total > 0" :total="total" v-model:page="queryParams.pageNum" v-model:limit="queryParams.pageSize" @pagination="getList" />
    </div>
    <el-dialog :title="title" v-model="open" width="700px" append-to-body><el-form ref="formRef" :model="form" :rules="rules" label-width="120px"><el-row :gutter="20"><el-col :span="12"><el-form-item label="质检编号" prop="qcNo"><el-input v-model="form.qcNo" placeholder="自动生成" disabled /></el-form-item></el-col><el-col :span="12"><el-form-item label="工单编号" prop="workOrderNo"><el-input v-model="form.workOrderNo" placeholder="请输入" /></el-form-item></el-col></el-row><el-row :gutter="20"><el-col :span="12"><el-form-item label="工序名称" prop="processName"><el-input v-model="form.processName" placeholder="请输入" /></el-form-item></el-col><el-col :span="12"><el-form-item label="类型" prop="qcType"><el-select v-model="form.qcType" placeholder="请选择"><el-option v-for="d in mms_qc_type" :key="d.value" :label="d.label" :value="d.value" /></el-select></el-form-item></el-col></el-row><el-row :gutter="20"><el-col :span="8"><el-form-item label="检验数量" prop="inspectQty"><el-input-number v-model="form.inspectQty" :min="0" :precision="2" style="width: 100%" /></el-form-item></el-col><el-col :span="8"><el-form-item label="不良数" prop="defectQty"><el-input-number v-model="form.defectQty" :min="0" :precision="2" style="width: 100%" /></el-form-item></el-col><el-col :span="8"><el-form-item label="报废数量" prop="scrapQty"><el-input-number v-model="form.scrapQty" :min="0" :precision="2" style="width: 100%" /></el-form-item></el-col></el-row><el-row :gutter="20"><el-col :span="12"><el-form-item label="缺陷类型" prop="defectType"><el-input v-model="form.defectType" placeholder="请输入" /></el-form-item></el-col><el-col :span="12"><el-form-item label="检验结果" prop="qcResult"><el-select v-model="form.qcResult" placeholder="请选择"><el-option v-for="d in mms_qc_result" :key="d.value" :label="d.label" :value="d.value" /></el-select></el-form-item></el-col></el-row><el-row :gutter="20"><el-col :span="12"><el-form-item label="检验人" prop="qcBy"><el-input v-model="form.qcBy" placeholder="请输入" /></el-form-item></el-col><el-col :span="12"><el-form-item label="检验时间" prop="qcTime"><el-date-picker v-model="form.qcTime" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" placeholder="选择时间" style="width: 100%" /></el-form-item></el-col></el-row><el-form-item label="备注" prop="remark"><el-input v-model="form.remark" type="textarea" placeholder="请输入" /></el-form-item></el-form><template #footer><div class="dialog-footer"><el-button type="primary" @click="submitForm">确 定</el-button><el-button @click="cancel">取 消</el-button></div></template></el-dialog>
    <el-dialog v-model="showStatusHelp" title="质检管理业务操作说明" width="820px" append-to-body><div class="status-help-content"><h4>一、质检管理释义</h4><div class="highlight-card highlight-primary"><div class="highlight-card-title">什么是质检管理？</div><div class="highlight-card-body"><strong>质检管理（Quality Control）</strong>是生产管控中记录生产过程质量检验数据的单据。覆盖首件检验（首检）、过程巡检（巡检）、完工检验（完工检）等多种检验类型，记录检验数量、不良数和检验结果，支持生产过程质量管控和数据追溯。<br/><br/>质检管理遵循 <strong>ISO 9001 质量管理体系</strong>要求，通过首检确认生产条件、巡检监控过程稳定性、完工检保障成品质量，实现生产全过程的质量数据采集和追溯。</div></div><h4>二、重点业务规则</h4><div class="highlight-card highlight-warning"><div class="highlight-card-title">核心规则</div><div class="highlight-card-body"><p>• <strong>检验类型：</strong>支持首检、巡检、完工检等多种检验类型</p><p>• <strong>不良数监控：</strong>不良数大于0时自动标红显示</p><p>• <strong>检验结果：</strong>合格、不合格、让步接收三种结果</p><p>• <strong>工单关联：</strong>质检记录需关联生产工单，确保数据可追溯</p></div></div><h4>三、新增/修改表单填写指南</h4><div class="highlight-card highlight-warning"><div class="highlight-card-title">基本信息区</div><div class="highlight-card-body"><p>• <strong>质检编号：</strong>质检记录的唯一标识编号，保存后由系统自动生成</p><p>• <strong>工单编号：</strong>关联的生产工单编号<span style="color: #f56c6c;">*必填</span></p><p>• <strong>工序名称：</strong>检验对应的工序名称</p><p>• <strong>类型：</strong>检验类型，包括首检、巡检、完工检等<span style="color: #f56c6c;">*必填</span></p></div></div><div class="highlight-card highlight-primary" style="margin-top: 12px;"><div class="highlight-card-title">检验数据区</div><div class="highlight-card-body"><p>• <strong>检验数量：</strong>本次检验的抽样数量<span style="color: #f56c6c;">*必填</span></p><p>• <strong>不良数：</strong>检验中发现的不合格品数量，大于0时自动标红<span style="color: #f56c6c;">*必填</span></p><p>• <strong>报废数量：</strong>检验中确定的报废数量</p><p>• <strong>缺陷类型：</strong>检验发现的主要缺陷类型描述</p></div></div><div class="highlight-card highlight-primary" style="margin-top: 12px;"><div class="highlight-card-title">检验结果区</div><div class="highlight-card-body"><p>• <strong>检验结果：</strong>检验的最终判定结果，包括合格、不合格、让步接收<span style="color: #f56c6c;">*必填</span></p><p>• <strong>检验人：</strong>执行检验的人员<span style="color: #f56c6c;">*必填</span></p><p>• <strong>检验时间：</strong>执行检验的时间</p></div></div><div class="highlight-card highlight-warning" style="margin-top: 12px;"><div class="highlight-card-title">其他信息区</div><div class="highlight-card-body"><p>• <strong>备注：</strong>检验的补充说明信息</p></div></div><h4>四、业务操作流程</h4><el-timeline><el-timeline-item type="primary" :hollow="true"><strong>创建质检记录：</strong>点击「新增」创建质检记录，填写工单编号、工序和检验类型</el-timeline-item><el-timeline-item type="warning" :hollow="true"><strong>记录检验数据：</strong>填写检验数量、不良数、报废数量和缺陷类型</el-timeline-item><el-timeline-item type="success" :hollow="true"><strong>判定结果：</strong>根据检验数据判定检验结果（合格/不合格/让步接收），记录检验人和检验时间</el-timeline-item></el-timeline></div><template #footer><el-button type="primary" @click="showStatusHelp = false">我知道了</el-button></template></el-dialog>
  </div>
</template>

<script setup name="Qc">
import { listQc, getQc, addQc, updateQc, delQc } from "@/api/mms/qc";
import { useColumnResize } from '@/composables/useColumnResize'
import { Search, Filter, RefreshLeft, ArrowDown, WarningFilled, ArrowRight, QuestionFilled } from '@element-plus/icons-vue'

const { proxy } = getCurrentInstance();
const { mms_qc_type, mms_qc_result } = proxy.useDict("mms_qc_type", "mms_qc_result");
const { colWidth, onHeaderDragEnd, tableRef, applySavedWidths } = useColumnResize('mms_qc_index')

const dataList = ref([]); const open = ref(false); const loading = ref(true); const showSearch = ref(true); const showAdvanced = ref(false);
const ids = ref([]); const single = ref(true); const multiple = ref(true); const total = ref(0); const title = ref("");
const dateRange = ref([]); const activeStatusTab = ref("all"); const statusCounts = ref({}); const showStatusHelp = ref(false);

const statusTabList = computed(() => mms_qc_result.value ? mms_qc_result.value.map(d => ({ label: d.label, value: d.value })) : []);
const defaultColumns = { qcNo: { label: '质检编号', visible: true }, workOrderNo: { label: '工单编号', visible: true }, processName: { label: '工序', visible: true }, qcType: { label: '类型', visible: true }, inspectQty: { label: '检验数量', visible: true }, defectQty: { label: '不良数', visible: true }, qcResult: { label: '检验结果', visible: true }, qcBy: { label: '检验人', visible: true }, createTime: { label: '创建时间', visible: true } }
function loadColumnVisibility() { try { const saved = localStorage.getItem('mms_qc_columns'); if (saved) { const parsed = JSON.parse(saved); const result = {}; Object.keys(defaultColumns).forEach(key => { result[key] = { label: defaultColumns[key].label, visible: parsed[key] !== undefined ? parsed[key] : defaultColumns[key].visible } }); return result } } catch (e) {} return { ...defaultColumns } }
const columns = ref(loadColumnVisibility())
const activeFilterCount = computed(() => { let c = 0; if (queryParams.value.qcNo) c++; if (queryParams.value.workOrderNo) c++; if (queryParams.value.processName) c++; if (queryParams.value.qcType) c++; if (queryParams.value.qcResult) c++; if (queryParams.value.qcBy) c++; if (dateRange.value && dateRange.value.length === 2) c++; return c; });

const data = reactive({ form: {}, queryParams: { pageNum: 1, pageSize: 10, qcNo: undefined, workOrderNo: undefined, processName: undefined, qcType: undefined, qcResult: undefined, qcBy: undefined, params: {} }, rules: { qcNo: [{ required: true, message: "请输入质检编号", trigger: "blur" }], workOrderNo: [{ required: true, message: "请输入工单编号", trigger: "blur" }] } });
const { queryParams, form, rules } = toRefs(data);

function getList() { loading.value = true; listQc(proxy.addDateRange(queryParams.value, dateRange.value)).then(response => { dataList.value = response.rows; total.value = response.total; loading.value = false; applySavedWidths(); updateStatusCounts(response.rows); }); }
function updateStatusCounts(rows) { const counts = { all: total.value }; if (mms_qc_result.value) { mms_qc_result.value.forEach(d => { counts[d.value] = rows.filter(r => r.qcResult === d.value).length; }); } statusCounts.value = counts; }
function handleQuery() { showAdvanced.value = false; queryParams.value.pageNum = 1; getList(); }
function resetQuery() { queryParams.value.qcNo = undefined; queryParams.value.workOrderNo = undefined; queryParams.value.processName = undefined; queryParams.value.qcType = undefined; queryParams.value.qcResult = undefined; queryParams.value.qcBy = undefined; dateRange.value = []; queryParams.value.params = {}; activeStatusTab.value = 'all'; handleQuery(); }
function handleStatusTabClick(status) { activeStatusTab.value = status; queryParams.value.qcResult = status === "all" ? undefined : status; handleQuery(); }
function handleSelectionChange(selection) { ids.value = selection.map(item => item.qcId); single.value = selection.length !== 1; multiple.value = !selection.length; }
function reset() { form.value = { qcNo: undefined, workOrderNo: undefined, processName: undefined, qcType: undefined, inspectQty: undefined, defectQty: undefined, scrapQty: undefined, defectType: undefined, qcResult: undefined, qcBy: undefined, qcTime: undefined, remark: undefined }; proxy.resetForm("formRef"); }
function handleAdd() { reset(); open.value = true; title.value = "新增质检"; }
function handleUpdate(row) { reset(); const id = row.qcId || ids.value[0]; getQc(id).then(response => { form.value = response.data; open.value = true; title.value = "修改质检"; }); }
function submitForm() { proxy.$refs["formRef"].validate(valid => { if (valid) { if (form.value.qcId != null) { updateQc(form.value).then(() => { proxy.$modal.msgSuccess("修改成功"); open.value = false; getList(); }); } else { addQc(form.value).then(() => { proxy.$modal.msgSuccess("新增成功"); open.value = false; getList(); }); } } }); }
function cancel() { open.value = false; reset(); }
function handleDelete(row) { const delIds = row.qcId || ids.value; proxy.$modal.confirm('是否确认删除选中的质检记录？').then(() => delQc(delIds)).then(() => { getList(); proxy.$modal.msgSuccess("删除成功"); }).catch(() => {}); }
function handleExport() { proxy.download("mms/qc/export", { ...queryParams.value }, `qc_${new Date().getTime()}.xlsx`); }
function dictLabel(dictRef, value) { if (!dictRef || !dictRef.value) return '-'; const item = dictRef.value.find(d => d.value == value); return item ? item.label : '-'; }
function resultBadgeClass(result) { const map = { '0': 'green', '1': 'red', '2': 'amber' }; return map[result] || 'gray'; }
function resultTabClass(value) { const map = { '0': 'tab-done', '1': 'tab-reject', '2': 'tab-draft' }; return map[value] || ''; }

getList();
</script>

<style src="@/composables/mms-list-styles.scss" lang="scss" scoped></style>
<style scoped>
.mms-qc-page{padding-top:10px;--brand-50:#eef2ff;--brand-100:#e0e7ff;--brand-200:#c7d2fe;--brand-500:#6366f1;--brand-600:#4f46e5;--brand-700:#4338ca;--ink-900:#0f172a;--ink-700:#334155;--ink-500:#64748b;--ink-400:#94a3b8;--ink-300:#cbd5e1;--ink-200:#e2e8f0;--ink-100:#f1f5f9;--ink-50:#f8fafc;--amber-50:#fffbeb;--amber-500:#f59e0b;--amber-700:#b45309;--blue-50:#eff6ff;--blue-500:#3b82f6;--blue-700:#1d4ed8;--green-50:#ecfdf5;--green-500:#10b981;--green-700:#047857;--red-50:#fef2f2;--red-500:#ef4444;--red-700:#b91c1c;--r-sm:6px;--r-md:10px;--r-lg:14px;--shadow-card:0 1px 0 rgba(15,23,42,.04),0 1px 2px rgba(15,23,42,.04);--ease-out:cubic-bezier(.16,.84,.44,1);font-feature-settings:"tnum" 1;color:var(--ink-900)}
</style>