-- 修复 wms_supplier 表结构，补充缺失的列
ALTER TABLE wms_supplier
ADD COLUMN supplier_short_name VARCHAR(128) COMMENT '供应商简称' AFTER supplier_name,
ADD COLUMN supplier_type VARCHAR(20) DEFAULT '0' COMMENT '供应商类型' AFTER supplier_short_name,
ADD COLUMN supplier_level VARCHAR(10) COMMENT '供应商等级' AFTER supplier_type,
ADD COLUMN unified_credit_code VARCHAR(64) COMMENT '统一社会信用代码' AFTER supplier_level,
ADD COLUMN email VARCHAR(128) COMMENT '邮箱' AFTER contact_phone,
ADD COLUMN fax VARCHAR(20) COMMENT '传真' AFTER email,
ADD COLUMN website VARCHAR(255) COMMENT '网址' AFTER fax,
ADD COLUMN postcode VARCHAR(10) COMMENT '邮政编码' AFTER website,
ADD COLUMN legal_person VARCHAR(64) COMMENT '法人代表' AFTER address,
ADD COLUMN registered_capital DECIMAL(18,2) DEFAULT 0 COMMENT '注册资本（万元）' AFTER legal_person,
ADD COLUMN enterprise_nature VARCHAR(20) COMMENT '企业性质' AFTER registered_capital,
ADD COLUMN business_scope VARCHAR(1000) COMMENT '经营范围' AFTER enterprise_nature,
ADD COLUMN established_date DATE COMMENT '成立日期' AFTER business_scope,
ADD COLUMN bank_name VARCHAR(128) COMMENT '开户银行' AFTER established_date,
ADD COLUMN bank_branch VARCHAR(128) COMMENT '开户支行' AFTER bank_name,
ADD COLUMN bank_account VARCHAR(64) COMMENT '银行账号' AFTER bank_branch,
ADD COLUMN tax_number VARCHAR(64) COMMENT '税号' AFTER bank_account,
ADD COLUMN invoice_title VARCHAR(255) COMMENT '发票抬头' AFTER tax_number,
ADD COLUMN invoice_address VARCHAR(500) COMMENT '发票地址' AFTER invoice_title,
ADD COLUMN invoice_phone VARCHAR(20) COMMENT '发票联系电话' AFTER invoice_address,
ADD COLUMN payment_method VARCHAR(20) DEFAULT '0' COMMENT '付款方式' AFTER invoice_phone,
ADD COLUMN payment_days INT DEFAULT 0 COMMENT '账期天数' AFTER payment_method,
ADD COLUMN settlement_type VARCHAR(20) DEFAULT '0' COMMENT '结算方式' AFTER payment_days,
ADD COLUMN currency VARCHAR(10) DEFAULT 'CNY' COMMENT '结算币种' AFTER settlement_type,
ADD COLUMN delivery_cycle INT COMMENT '交货周期' AFTER currency,
ADD COLUMN min_order_amount DECIMAL(18,2) DEFAULT 0 COMMENT '最小订单金额' AFTER delivery_cycle,
ADD COLUMN cooperation_date DATE COMMENT '合作开始日期' AFTER min_order_amount,
ADD COLUMN qualification_status CHAR(1) DEFAULT '0' COMMENT '资质状态' AFTER cooperation_date,
ADD INDEX idx_supplier_type (supplier_type),
ADD INDEX idx_supplier_level (supplier_level),
ADD INDEX idx_unified_credit_code (unified_credit_code);
