const fs = require('fs');
const f = 'e:/AIcode/EDOP/RuoYi/RuoYi-Vue3/ruoyi-ui/src/views/hr/employee/index.vue';
const w = [];
const p = (s) => w.push(s);

// 查看详情弹窗
p('    <el-dialog v-model="viewOpen" width="960px" append-to-body draggable class="rd-dialog">');
p('      <template #header><div class="rd-detail-header"><div class="rd-detail-header-icon"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg></div><div class="rd-detail-header-main"><div class="rd-detail-header-title">员工详情</div><div class="rd-detail-header-sub" v-if="viewData.employeeNo"><div class="rd-detail-header-divider"></div><span class="rd-detail-header-no">工号：{{ viewData.employeeNo }}</span><span class="rd-detail-header-no">姓名：{{ viewData.employeeName }}</span></div></div></div></template>');
p('      <div class="rd-page"><el-tabs v-model="activeTab" class="detail-tabs">');
// 基本信息
p('        <el-tab-pane label="基本信息" name="basic">');
p('          <section class="rd-card"><div class="rd-card-header"><div class="rd-card-title"><span class="rd-card-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg></span>核心信息</div></div>');
p('            <div class="rd-card-body" style="display:block"><div class="rd-grid">');
p('              <div class="rd-item"><span class="rd-label">工号</span><div class="rd-value">{{ viewData.employeeNo || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">姓名</span><div class="rd-value">{{ viewData.employeeName || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">性别</span><div class="rd-value">{{ viewData.gender || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">出生日期</span><div class="rd-value">{{ viewData.birthday || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">民族</span><div class="rd-value">{{ viewData.nation || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">联系电话</span><div class="rd-value">{{ viewData.phone || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">邮箱</span><div class="rd-value">{{ viewData.email || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">岗位</span><div class="rd-value">{{ viewData.positionName || \'-\' }}</div></div>');
p('            </div></div></section>');
p('          <section class="rd-card"><div class="rd-card-header"><div class="rd-card-title"><span class="rd-card-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M16 11V7a4 4 0 0 0-8 0V11"/><rect x="3" y="11" width="18" height="11" rx="2" ry="2"/></svg></span>联系信息</div></div>');
p('            <div class="rd-card-body" style="display:block"><div class="rd-grid">');
p('              <div class="rd-item"><span class="rd-label">紧急联系人</span><div class="rd-value">{{ viewData.emergencyContact || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">紧急电话</span><div class="rd-value">{{ viewData.emergencyPhone || \'-\' }}</div></div>');
p('              <div class="rd-item rd-item--full"><span class="rd-label">现住址</span><div class="rd-value">{{ viewData.address || \'-\' }}</div></div>');
p('            </div></div></section>');
p('        </el-tab-pane>');
// 个人信息
p('        <el-tab-pane label="个人信息" name="personal">');
p('          <section class="rd-card"><div class="rd-card-header"><div class="rd-card-title"><span class="rd-card-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg></span>个人资料</div></div>');
p('            <div class="rd-card-body" style="display:block"><div class="rd-grid">');
p('              <div class="rd-item"><span class="rd-label">身份证号</span><div class="rd-value">{{ viewData.idCard || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">性别</span><div class="rd-value">{{ viewData.gender || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">民族</span><div class="rd-value">{{ viewData.nation || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">政治面貌</span><div class="rd-value">{{ viewData.politicsStatus || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">婚姻状况</span><div class="rd-value">{{ viewData.maritalStatus || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">籍贯</span><div class="rd-value">{{ viewData.nativePlace || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">学历</span><div class="rd-value">{{ viewData.eduLevel || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">毕业院校</span><div class="rd-value">{{ viewData.graduationSchool || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">专业</span><div class="rd-value">{{ viewData.major || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">毕业日期</span><div class="rd-value">{{ viewData.graduationDate || \'-\' }}</div></div>');
p('            </div></div></section>');
// 家庭成员
p('          <section class="rd-card"><div class="rd-card-header"><div class="rd-card-title"><span class="rd-card-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg></span>家庭成员</div></div>');
p('            <div class="rd-card-body" style="display:block">');
p('              <el-table :data="viewData.familyList || []" border size="small" v-if="viewData.familyList && viewData.familyList.length">');
p('                <el-table-column label="序号" type="index" width="85" align="center" />');
p('                <el-table-column label="姓名" prop="memberName" align="center" min-width="100" />');
p('                <el-table-column label="关系" prop="relationship" align="center" width="100" />');
p('                <el-table-column label="性别" prop="gender" align="center" width="80" />');
p('                <el-table-column label="出生日期" prop="birthday" align="center" width="120" />');
p('                <el-table-column label="联系电话" prop="phone" align="center" width="120" />');
p('                <el-table-column label="工作单位/职业" prop="occupation" align="center" min-width="150" show-overflow-tooltip />');
p('              </el-table>');
p('              <div class="rd-empty" v-else><svg class="rd-empty-icon" width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/></svg><p class="rd-empty-text">暂无家庭成员信息</p></div>');
p('            </div></section>');
p('        </el-tab-pane>');
// 工作信息
p('        <el-tab-pane label="工作信息" name="work">');
p('          <section class="rd-card"><div class="rd-card-header"><div class="rd-card-title"><span class="rd-card-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="7" width="20" height="14" rx="2" ry="2"/><path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"/></svg></span>工作信息</div></div>');
p('            <div class="rd-card-body" style="display:block"><div class="rd-grid">');
p('              <div class="rd-item"><span class="rd-label">入职日期</span><div class="rd-value">{{ viewData.entryDate || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">转正日期</span><div class="rd-value">{{ viewData.regularDate || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">离职日期</span><div class="rd-value">{{ viewData.leaveDate || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">员工状态</span><div class="rd-value">{{ viewData.employeeStatus || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">用工类型</span><div class="rd-value">{{ viewData.employeeType || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">工时制度</span><div class="rd-value">{{ viewData.workType || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">技能等级</span><div class="rd-value">{{ viewData.skillLevel || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">社会工龄</span><div class="rd-value">{{ viewData.socialWorkYears != null ? viewData.socialWorkYears + \' 年\' : \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">本公司工龄</span><div class="rd-value">{{ viewData.companyWorkYears != null ? viewData.companyWorkYears + \' 年\' : \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">离职原因</span><div class="rd-value">{{ viewData.leaveReason || \'-\' }}</div></div>');
p('            </div></div></section>');
// 银行社保
p('          <section class="rd-card"><div class="rd-card-header"><div class="rd-card-title"><span class="rd-card-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="5" width="20" height="14" rx="2"/><line x1="2" y1="10" x2="22" y2="10"/></svg></span>银行与社保</div></div>');
p('            <div class="rd-card-body" style="display:block"><div class="rd-grid">');
p('              <div class="rd-item"><span class="rd-label">开户银行</span><div class="rd-value">{{ viewData.bankName || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">银行卡号</span><div class="rd-value">{{ viewData.bankAccount || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">社保号</span><div class="rd-value">{{ viewData.socialSecurityNo || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">参保状态</span><div class="rd-value">{{ viewData.socialSecurityStatus || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">公积金号</span><div class="rd-value">{{ viewData.houseFundNo || \'-\' }}</div></div>');
p('              <div class="rd-item"><span class="rd-label">黑名单</span><div class="rd-value">{{ viewData.blacklistFlag === \'1\' ? \'是\' : \'否\' }}</div></div>');
p('              <div class="rd-item rd-item--full"><span class="rd-label">黑名单原因</span><div class="rd-value">{{ viewData.blacklistReason || \'-\' }}</div></div>');
p('            </div></div></section>');
// 教育背景
p('          <section class="rd-card"><div class="rd-card-header"><div class="rd-card-title"><span class="rd-card-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 10v6M2 10l10-5 10 5-10 5z"/><path d="M6 12v5c3 3 9 3 12 0v-5"/></svg></span>教育背景</div></div>');
p('            <div class="rd-card-body" style="display:block">');
p('              <el-table :data="viewData.educationList || []" border size="small" v-if="viewData.educationList && viewData.educationList.length">');
p('                <el-table-column label="序号" type="index" width="85" align="center" />');
p('                <el-table-column label="开始日期" prop="startDate" align="center" width="120" />');
p('                <el-table-column label="结束日期" prop="endDate" align="center" width="120" />');
p('                <el-table-column label="学校名称" prop="schoolName" align="center" min-width="150" show-overflow-tooltip />');
p('                <el-table-column label="专业" prop="major" align="center" min-width="120" show-overflow-tooltip />');
p('                <el-table-column label="学历" prop="eduLevel" align="center" width="100" />');
p('                <el-table-column label="学位" prop="degree" align="center" width="100" />');
p('                <el-table-column label="最高学历" prop="isHighest" align="center" width="100"><template #default="scope">{{ scope.row.isHighest === \'1\' ? \'是\' : \'否\' }}</template></el-table-column>');
p('              </el-table>');
p('              <div class="rd-empty" v-else><svg class="rd-empty-icon" width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M22 10v6M2 10l10-5 10 5-10 5z"/><path d="M6 12v5c3 3 9 3 12 0v-5"/></svg><p class="rd-empty-text">暂无教育背景信息</p></div>');
p('            </div></section>');
// 工作经历
p('          <section class="rd-card"><div class="rd-card-header"><div class="rd-card-title"><span class="rd-card-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="7" width="20" height="14" rx="2" ry="2"/><path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"/></svg></span>工作经历</div></div>');
p('            <div class="rd-card-body" style="display:block">');
p('              <el-table :data="viewData.workExpList || []" border size="small" v-if="viewData.workExpList && viewData.workExpList.length">');
p('                <el-table-column label="序号" type="index" width="85" align="center" />');
p('                <el-table-column label="开始日期" prop="startDate" align="center" width="120" />');
p('                <el-table-column label="结束日期" prop="endDate" align="center" width="120" />');
p('                <el-table-column label="工作单位" prop="companyName" align="center" min-width="150" show-overflow-tooltip />');
p('                <el-table-column label="职位" prop="position" align="center" min-width="120" />');
p('                <el-table-column label="工作内容" prop="workContent" align="center" min-width="200" show-overflow-tooltip />');
p('                <el-table-column label="离职原因" prop="leaveReason" align="center" min-width="150" show-overflow-tooltip />');
p('              </el-table>');
p('              <div class="rd-empty" v-else><svg class="rd-empty-icon" width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="2" y="7" width="20" height="14" rx="2" ry="2"/><path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"/></svg><p class="rd-empty-text">暂无工作经历信息</p></div>');
p('            </div></section>');
// 培训/职称/资格认证
p('          <section class="rd-card"><div class="rd-card-header"><div class="rd-card-title"><span class="rd-card-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9 11H7v6h2v-6zm4 0h-2v6h2v-6zm4 0h-2v6h2v-6z"/><path d="M21 12V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v7"/></svg></span>培训/职称/资格认证</div></div>');
p('            <div class="rd-card-body" style="display:block">');
p('              <el-table :data="viewData.qualificationList || []" border size="small" v-if="viewData.qualificationList && viewData.qualificationList.length">');
p('                <el-table-column label="序号" type="index" width="85" align="center" />');
p('                <el-table-column label="类型" prop="qualType" align="center" width="100" />');
p('                <el-table-column label="名称" prop="qualName" align="center" min-width="150" show-overflow-tooltip />');
p('                <el-table-column label="证书编号" prop="qualNo" align="center" width="120" />');
p('                <el-table-column label="发证机构" prop="issueOrg" align="center" min-width="150" show-overflow-tooltip />');
p('                <el-table-column label="发证日期" prop="issueDate" align="center" width="120" />');
p('                <el-table-column label="有效期至" prop="validTo" align="center" width="120" />');
p('                <el-table-column label="成绩/等级" prop="score" align="center" width="100" />');
p('              </el-table>');
p('              <div class="rd-empty" v-else><svg class="rd-empty-icon" width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M9 11H7v6h2v-6zm4 0h-2v6h2v-6z"/><path d="M21 12V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v7"/></svg><p class="rd-empty-text">暂无培训/职称/资格认证信息</p></div>');
p('            </div></section>');
p('        </el-tab-pane>');
p('      </el-tabs></div>');
p('      <template #footer><el-button @click="viewOpen = false">关 闭</el-button></template>');
p('    </el-dialog>');
p('  </div>');
p('</template>');
p('');
// script
p('<script setup name="HrEmployee">');
p('import { listHrEmployee, getHrEmployee, addHrEmployee, updateHrEmployee, delHrEmployee } from \'@/api/hr/hrEmployee\'');
p('import { useDetailCard } from \'@/composables/useDetailCard\'');
p('');
p('const { proxy } = getCurrentInstance()');
p('const { collapsedCards, toggleCard } = useDetailCard([\'c0\', \'c1\', \'c2\', \'c3\'])');
p('');
p('const hrEmployeeList = ref([])');
p('const open = ref(false)');
p('const viewOpen = ref(false)');
p('const viewData = ref({})');
p('const activeTab = ref(\'basic\')');
p('const loading = ref(true)');
p('const showSearch = ref(true)');
p('const ids = ref([])');
p('const single = ref(true)');
p('const multiple = ref(true)');
p('const total = ref(0)');
p('const title = ref(\'\')');
p('');
p('const activeFilterCount = computed(() => { let c = 0; if (queryParams.value.employeeNo) c++; if (queryParams.value.employeeName) c++; if (queryParams.value.idCard) c++; if (queryParams.value.employeeStatus) c++; return c; })');
p('');
p('const data = reactive({');
p('  form: {},');
p('  queryParams: { pageNum: 1, pageSize: 10, employeeNo: undefined, employeeName: undefined, idCard: undefined, employeeStatus: undefined },');
p('  rules: {');
p('    employeeNo: [{ required: true, message: \'工号不能为空\', trigger: \'blur\' }],');
p('    employeeName: [{ required: true, message: \'姓名不能为空\', trigger: \'blur\' }]');
p('  }');
p('})');
p('const { queryParams, form, rules } = toRefs(data)');
p('');
p('function getList() {');
p('  loading.value = true');
p('  listHrEmployee(queryParams.value).then(response => {');
p('    hrEmployeeList.value = response.rows');
p('    total.value = response.total');
p('    loading.value = false');
p('  }).catch(() => { loading.value = false })');
p('}');
p('');
p('function handleQuery() { queryParams.value.pageNum = 1; getList() }');
p('function resetQuery() { queryParams.value.employeeNo = undefined; queryParams.value.employeeName = undefined; queryParams.value.idCard = undefined; queryParams.value.employeeStatus = undefined; handleQuery() }');
p('function handleSelectionChange(selection) { ids.value = selection.map(item => item.employeeId); single.value = selection.length !== 1; multiple.value = !selection.length }');
p('');
p('function reset() {');
p('  form.value = { employeeNo: undefined, employeeName: undefined, gender: undefined, idCard: undefined, birthday: undefined, nation: undefined, politicsStatus: undefined, maritalStatus: undefined, phone: undefined, email: undefined, emergencyContact: undefined, emergencyPhone: undefined, nativePlace: undefined, address: undefined, eduLevel: undefined, graduationSchool: undefined, major: undefined, graduationDate: undefined, socialWorkYears: undefined, companyWorkYears: undefined, orgId: undefined, positionId: undefined, positionName: undefined, skillLevel: undefined, workType: undefined, employeeType: undefined, entryDate: undefined, regularDate: undefined, leaveDate: undefined, employeeStatus: undefined, bankName: undefined, bankAccount: undefined, socialSecurityNo: undefined, socialSecurityStatus: undefined, houseFundNo: undefined, leaveReason: undefined, blacklistFlag: undefined, blacklistReason: undefined, userId: undefined, photo: undefined }');
p('  proxy.resetForm(\'hrEmployeeRef\')');
p('}');
p('');
p('function handleAdd() { reset(); open.value = true; title.value = \'添加员工\' }');
p('function handleUpdate(row) { reset(); const employeeId = row.employeeId || ids.value[0]; getHrEmployee(employeeId).then(response => { form.value = response.data; open.value = true; title.value = \'修改员工\' }) }');
p('function handleView(row) { const employeeId = row.employeeId || ids.value[0]; getHrEmployee(employeeId).then(response => { viewData.value = response.data; activeTab.value = \'basic\'; viewOpen.value = true }) }');
p('');
p('function submitForm() {');
p('  proxy.$refs[\'hrEmployeeRef\'].validate(valid => {');
p('    if (valid) {');
p('      if (form.value.employeeId != undefined) {');
p('        updateHrEmployee(form.value).then(() => { proxy.$modal.msgSuccess(\'修改成功\'); open.value = false; getList() })');
p('      } else {');
p('        addHrEmployee(form.value).then(() => { proxy.$modal.msgSuccess(\'新增成功\'); open.value = false; getList() })');
p('      }');
p('    }');
p('  })');
p('}');
p('');
p('function handleDelete(row) {');
p('  const employeeIds = row.employeeId || ids.value');
p('  proxy.$modal.confirm(\'是否确认删除选中的员工档案？\').then(function() { return delHrEmployee(employeeIds) }).then(() => { getList(); proxy.$modal.msgSuccess(\'删除成功\') }).catch(() => {})');
p('}');
p('');
p('function handleExport() { proxy.download(\'hr/employee/export\', { ...queryParams.value }, `hrEmployee_${new Date().getTime()}.xlsx`) }');
p('function cancel() { open.value = false; reset() }');
p('');
p('getList()');
p('</script>');
p('');
// style
p('<style scoped>');
p('.hr-employee-page { --brand-50:#eef2ff; --brand-100:#e0e7ff; --brand-200:#c7d2fe; --brand-500:#6366f1; --brand-600:#4f46e5; --brand-700:#4338ca; --ink-900:#0f172a; --ink-700:#334155; --ink-500:#64748b; --ink-400:#94a3b8; --ink-300:#cbd5e1; --ink-200:#e2e8f0; --ink-100:#f1f5f9; --ink-50:#f8fafc; --amber-50:#fffbeb; --amber-500:#f59e0b; --amber-700:#b45309; --blue-50:#eff6ff; --blue-500:#3b82f6; --blue-700:#1d4ed8; --green-50:#ecfdf5; --green-500:#10b981; --green-700:#047857; --red-50:#fef2f2; --red-500:#ef4444; --red-700:#b91c1c; --violet-50:#f5f3ff; --r-sm:6px; --r-md:10px; --r-lg:14px; --shadow-card:0 1px 0 rgba(15,23,42,.04),0 1px 2px rgba(15,23,42,.04); --ease-out:cubic-bezier(.16,.84,.44,1); padding-top:10px; color:var(--ink-900); font-feature-settings:"tnum" 1; }');
p('.hr-employee-page .surface { background:#fff; border:1px solid var(--ink-200); border-radius:var(--r-lg); box-shadow:var(--shadow-card); overflow:hidden; margin-bottom:8px; }');
p('.hr-employee-page .filter-card { padding:14px 20px 16px; }');
p('.hr-employee-page .filter-head { display:flex; align-items:center; justify-content:space-between; margin-bottom:12px; }');
p('.hr-employee-page .filter-title { font-size:16px; font-weight:700; color:var(--ink-900); display:flex; align-items:center; gap:8px; }');
p('.hr-employee-page .filter-title .glyph { width:4px; height:16px; border-radius:2px; background:var(--brand-500); }');
p('.hr-employee-page .filter-bar { display:grid; grid-template-columns:repeat(4,minmax(0,1fr)); gap:12px 16px; margin-bottom:12px; }');
p('.hr-employee-page .field { display:flex; flex-direction:column; gap:4px; }');
p('.hr-employee-page .field label { font-size:13px; font-weight:500; color:var(--ink-500); }');
p('.hr-employee-page .filter-actions { display:flex; align-items:center; justify-content:space-between; }');
p('.hr-employee-page .filter-info { font-size:13px; color:var(--ink-400); display:flex; align-items:center; gap:4px; }');
p('.hr-employee-page .toolbar { display:flex; align-items:center; justify-content:space-between; padding:10px 16px; border-bottom:1px solid var(--ink-200); }');
p('.hr-employee-page .toolbar .left { display:flex; gap:8px; }');
p('.hr-employee-page .app-table { --el-table-bg-color:#fff; --el-table-header-bg-color:var(--ink-50); --el-table-row-hover-bg-color:#fafbff; --el-table-border-color:transparent; --el-table-text-color:var(--ink-700); --el-table-header-text-color:var(--ink-500); }');
p('.hr-employee-page .app-table :deep(.el-table__body td) { border-right-color:transparent !important; }');
p('.hr-employee-page .app-table :deep(.el-table__header th) { border-right-color:transparent !important; }');
p('.hr-employee-page .badge { display:inline-flex; align-items:center; gap:5px; padding:3px 9px; border-radius:999px; font-size:13px; font-weight:600; line-height:1; border:1px solid transparent; }');
p('.hr-employee-page .badge.green { background:var(--green-50); color:var(--green-700); border-color:#a7f3d0; }');
p('.hr-employee-page .badge.red { background:var(--red-50); color:var(--red-700); border-color:#fecaca; }');
p('.hr-employee-page .badge.amber { background:var(--amber-50); color:var(--amber-700); border-color:#fde68a; }');
p('.hr-employee-page .badge.violet { background:var(--violet-50); color:var(--brand-700); border-color:var(--brand-200); }');
p('.hr-employee-page .badge.gray { background:var(--ink-100); color:var(--ink-500); border-color:var(--ink-200); }');
p(':deep(.col-action) { padding:6px 4px !important; }');
p(':deep(.col-action .cell) { display:flex; justify-content:center; padding:0; }');
p('.action-btn-row { display:inline-flex; flex-wrap:wrap; justify-content:center; gap:0; }');
p(':deep(.col-action .el-button) { padding:2px 4px; margin:0 2px; white-space:nowrap; justify-content:center; }');
p(':deep(.col-action .el-button + .el-button) { margin-left:2px; }');
p('.hr-employee-page .detail-tabs :deep(.el-tabs__header) { margin-bottom:8px; }');
p('</style>');

fs.appendFileSync(f, w.join('\n'), 'utf8');
console.log('Part 2 appended:', w.length, 'lines');
