const fs = require('fs');
const f = 'e:/AIcode/EDOP/RuoYi/RuoYi-Vue3/ruoyi-ui/src/views/hr/employee/index.vue';
const w = [];
const p = (s) => w.push(s);

p('<template>');
p('  <div class="app-container hr-employee-page">');
p('    <div class="surface filter-card" v-show="showSearch">');
p('      <div class="filter-head"><div class="filter-title"><span class="glyph"></span> 筛选条件</div></div>');
p('      <div class="filter-bar">');
p('        <div class="field"><label>工号</label><div class="control"><el-input v-model="queryParams.employeeNo" placeholder="请输入工号" clearable @keyup.enter="handleQuery" /></div></div>');
p('        <div class="field"><label>姓名</label><div class="control"><el-input v-model="queryParams.employeeName" placeholder="请输入姓名" clearable @keyup.enter="handleQuery" /></div></div>');
p('        <div class="field"><label>身份证号</label><div class="control"><el-input v-model="queryParams.idCard" placeholder="请输入身份证号" clearable @keyup.enter="handleQuery" /></div></div>');
p('        <div class="field"><label>员工状态</label><div class="control"><el-select v-model="queryParams.employeeStatus" placeholder="请选择" clearable style="width:100%"><el-option label="在职" value="在职" /><el-option label="试用" value="试用" /><el-option label="离职" value="离职" /></el-select></div></div>');
p('      </div>');
p('      <div class="filter-actions"><div class="filter-info"><el-icon><Filter /></el-icon> 已选 {{ activeFilterCount }} 个条件，支持回车快速搜索</div><div class="filter-buttons"><el-button icon="RefreshLeft" @click="resetQuery">重置</el-button><el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button></div></div>');
p('    </div>');
p('    <div class="surface">');
p('      <div class="toolbar"><div class="left">');
p('        <el-button type="primary" plain icon="Plus" @click="handleAdd" v-hasPermi="[\'hr:employee:add\']">新增</el-button>');
p('        <el-button type="success" plain icon="Edit" :disabled="single" @click="handleUpdate" v-hasPermi="[\'hr:employee:edit\']">修改</el-button>');
p('        <el-button type="danger" plain icon="Delete" :disabled="multiple" @click="handleDelete" v-hasPermi="[\'hr:employee:remove\']">删除</el-button>');
p('        <el-button type="warning" plain icon="Download" @click="handleExport" v-hasPermi="[\'hr:employee:export\']">导出</el-button>');
p('      </div><div class="right"><right-toolbar v-model:showSearch="showSearch" @queryTable="getList"></right-toolbar></div></div>');
p('      <div class="table-wrap">');
p('        <el-table v-loading="loading" :data="hrEmployeeList" @selection-change="handleSelectionChange" border class="app-table">');
p('          <el-table-column type="selection" width="55" align="center" />');
p('          <el-table-column label="序号" type="index" width="85" align="center" />');
p('          <el-table-column label="工号" prop="employeeNo" align="center" width="120" />');
p('          <el-table-column label="姓名" prop="employeeName" align="center" width="100" />');
p('          <el-table-column label="性别" prop="gender" align="center" width="80" />');
p('          <el-table-column label="部门/组织" prop="positionName" align="center" min-width="120" show-overflow-tooltip />');
p('          <el-table-column label="身份证号" prop="idCard" align="center" width="180" show-overflow-tooltip />');
p('          <el-table-column label="联系电话" prop="phone" align="center" width="120" />');
p('          <el-table-column label="入职日期" prop="entryDate" align="center" width="120" />');
p('          <el-table-column label="状态" prop="employeeStatus" align="center" width="100">');
p('            <template #default="scope">');
p('              <span class="badge green" v-if="scope.row.employeeStatus===\'在职\'">{{ scope.row.employeeStatus }}</span>');
p('              <span class="badge red" v-else-if="scope.row.employeeStatus===\'离职\'">{{ scope.row.employeeStatus }}</span>');
p('              <span class="badge amber" v-else>{{ scope.row.employeeStatus || \'-\' }}</span>');
p('            </template>');
p('          </el-table-column>');
p('          <el-table-column label="操作" width="180" align="center" fixed="right" class-name="col-action">');
p('            <template #default="scope"><div class="action-btn-row">');
p('              <el-button link type="primary" icon="View" @click="handleView(scope.row)" v-hasPermi="[\'hr:employee:query\']">详情</el-button>');
p('              <el-button link type="primary" icon="Edit" @click="handleUpdate(scope.row)" v-hasPermi="[\'hr:employee:edit\']">修改</el-button>');
p('              <el-button link type="danger" icon="Delete" @click="handleDelete(scope.row)" v-hasPermi="[\'hr:employee:remove\']">删除</el-button>');
p('            </div></template>');
p('          </el-table-column>');
p('        </el-table>');
p('      </div>');
p('      <div class="pagination-container"><pagination v-show="total>0" :total="total" v-model:page="queryParams.pageNum" v-model:limit="queryParams.pageSize" @pagination="getList" /></div>');
p('    </div>');
// 编辑弹窗
p('    <el-dialog v-model="open" width="900px" append-to-body draggable class="rd-dialog">');
p('      <template #header><div class="rd-detail-header"><div class="rd-detail-header-icon"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg></div><span class="rd-detail-header-title">{{ title }}</span></div></template>');
p('      <el-form ref="hrEmployeeRef" :model="form" :rules="rules" label-width="100px"><div class="rd-page">');
p('        <section class="rd-card"><div class="rd-card-header" @click="toggleCard(\'c0\')"><div class="rd-card-title"><span class="rd-card-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg></span>基本信息</div><button class="rd-collapse-btn" :class="{\'is-collapsed\':collapsedCards.c0}" aria-label="折叠"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="18 15 12 9 6 15"/></svg></button></div>');
p('          <div class="rd-card-body" v-show="!collapsedCards.c0"><el-row :gutter="20">');
p('            <el-col :span="12"><el-form-item label="工号" prop="employeeNo"><el-input v-model="form.employeeNo" placeholder="请输入工号" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="姓名" prop="employeeName"><el-input v-model="form.employeeName" placeholder="请输入姓名" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="性别" prop="gender"><el-select v-model="form.gender" placeholder="请选择" style="width:100%"><el-option label="男" value="男" /><el-option label="女" value="女" /></el-select></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="身份证号" prop="idCard"><el-input v-model="form.idCard" placeholder="请输入身份证号" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="出生日期" prop="birthday"><el-date-picker v-model="form.birthday" type="date" value-format="YYYY-MM-DD" placeholder="选择日期" style="width:100%" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="民族" prop="nation"><el-input v-model="form.nation" placeholder="请输入民族" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="联系电话" prop="phone"><el-input v-model="form.phone" placeholder="请输入联系电话" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="邮箱" prop="email"><el-input v-model="form.email" placeholder="请输入邮箱" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="所属组织ID" prop="orgId"><el-input-number v-model="form.orgId" :precision="0" :min="0" controls-position="right" style="width:100%" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="岗位名称" prop="positionName"><el-input v-model="form.positionName" placeholder="请输入岗位名称" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="员工状态" prop="employeeStatus"><el-select v-model="form.employeeStatus" placeholder="请选择" style="width:100%"><el-option label="在职" value="在职" /><el-option label="试用" value="试用" /><el-option label="离职" value="离职" /><el-option label="退休" value="退休" /></el-select></el-form-item></el-col>');
p('          </el-row></div></section>');
p('        <section class="rd-card"><div class="rd-card-header" @click="toggleCard(\'c1\')"><div class="rd-card-title"><span class="rd-card-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg></span>个人信息</div><button class="rd-collapse-btn" :class="{\'is-collapsed\':collapsedCards.c1}" aria-label="折叠"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="18 15 12 9 6 15"/></svg></button></div>');
p('          <div class="rd-card-body" v-show="!collapsedCards.c1"><el-row :gutter="20">');
p('            <el-col :span="12"><el-form-item label="政治面貌" prop="politicsStatus"><el-select v-model="form.politicsStatus" placeholder="请选择" style="width:100%"><el-option label="群众" value="群众" /><el-option label="党员" value="党员" /><el-option label="团员" value="团员" /></el-select></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="婚姻状况" prop="maritalStatus"><el-select v-model="form.maritalStatus" placeholder="请选择" style="width:100%"><el-option label="未婚" value="未婚" /><el-option label="已婚" value="已婚" /><el-option label="离异" value="离异" /></el-select></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="籍贯" prop="nativePlace"><el-input v-model="form.nativePlace" placeholder="请输入籍贯" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="现住址" prop="address"><el-input v-model="form.address" placeholder="请输入现住址" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="紧急联系人" prop="emergencyContact"><el-input v-model="form.emergencyContact" placeholder="请输入紧急联系人" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="紧急电话" prop="emergencyPhone"><el-input v-model="form.emergencyPhone" placeholder="请输入紧急电话" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="学历" prop="eduLevel"><el-input v-model="form.eduLevel" placeholder="请输入学历" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="毕业院校" prop="graduationSchool"><el-input v-model="form.graduationSchool" placeholder="请输入毕业院校" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="专业" prop="major"><el-input v-model="form.major" placeholder="请输入专业" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="毕业日期" prop="graduationDate"><el-date-picker v-model="form.graduationDate" type="date" value-format="YYYY-MM-DD" placeholder="选择日期" style="width:100%" /></el-form-item></el-col>');
p('          </el-row></div></section>');
p('        <section class="rd-card"><div class="rd-card-header" @click="toggleCard(\'c2\')"><div class="rd-card-title"><span class="rd-card-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="7" width="20" height="14" rx="2" ry="2"/><path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"/></svg></span>工作信息</div><button class="rd-collapse-btn" :class="{\'is-collapsed\':collapsedCards.c2}" aria-label="折叠"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="18 15 12 9 6 15"/></svg></button></div>');
p('          <div class="rd-card-body" v-show="!collapsedCards.c2"><el-row :gutter="20">');
p('            <el-col :span="12"><el-form-item label="入职日期" prop="entryDate"><el-date-picker v-model="form.entryDate" type="date" value-format="YYYY-MM-DD" placeholder="选择日期" style="width:100%" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="转正日期" prop="regularDate"><el-date-picker v-model="form.regularDate" type="date" value-format="YYYY-MM-DD" placeholder="选择日期" style="width:100%" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="离职日期" prop="leaveDate"><el-date-picker v-model="form.leaveDate" type="date" value-format="YYYY-MM-DD" placeholder="选择日期" style="width:100%" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="离职原因" prop="leaveReason"><el-input v-model="form.leaveReason" placeholder="请输入离职原因" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="用工类型" prop="employeeType"><el-select v-model="form.employeeType" placeholder="请选择" style="width:100%"><el-option label="正式工" value="正式工" /><el-option label="合同工" value="合同工" /><el-option label="临时工" value="临时工" /></el-select></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="工时制度" prop="workType"><el-select v-model="form.workType" placeholder="请选择" style="width:100%"><el-option label="标准工时" value="标准工时" /><el-option label="综合工时" value="综合工时" /></el-select></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="技能等级" prop="skillLevel"><el-input v-model="form.skillLevel" placeholder="请输入技能等级" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="社会工龄" prop="socialWorkYears"><el-input-number v-model="form.socialWorkYears" :precision="0" :min="0" controls-position="right" style="width:100%" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="本公司工龄" prop="companyWorkYears"><el-input-number v-model="form.companyWorkYears" :precision="0" :min="0" controls-position="right" style="width:100%" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="开户银行" prop="bankName"><el-input v-model="form.bankName" placeholder="请输入开户银行" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="银行卡号" prop="bankAccount"><el-input v-model="form.bankAccount" placeholder="请输入银行卡号" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="社保号" prop="socialSecurityNo"><el-input v-model="form.socialSecurityNo" placeholder="请输入社保号" /></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="公积金号" prop="houseFundNo"><el-input v-model="form.houseFundNo" placeholder="请输入公积金号" /></el-form-item></el-col>');
p('          </el-row></div></section>');
p('        <section class="rd-card"><div class="rd-card-header" @click="toggleCard(\'c3\')"><div class="rd-card-title"><span class="rd-card-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg></span>其他信息</div><button class="rd-collapse-btn" :class="{\'is-collapsed\':collapsedCards.c3}" aria-label="折叠"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="18 15 12 9 6 15"/></svg></button></div>');
p('          <div class="rd-card-body" v-show="!collapsedCards.c3"><el-row :gutter="20">');
p('            <el-col :span="12"><el-form-item label="黑名单" prop="blacklistFlag"><el-select v-model="form.blacklistFlag" placeholder="请选择" style="width:100%"><el-option label="否" value="0" /><el-option label="是" value="1" /></el-select></el-form-item></el-col>');
p('            <el-col :span="12"><el-form-item label="黑名单原因" prop="blacklistReason"><el-input v-model="form.blacklistReason" placeholder="请输入黑名单原因" /></el-form-item></el-col>');
p('            <el-col :span="24"><el-form-item label="备注" prop="remark"><el-input v-model="form.remark" type="textarea" :rows="2" placeholder="请输入备注" /></el-form-item></el-col>');
p('          </el-row></div></section>');
p('      </div></el-form>');
p('      <template #footer><el-button type="primary" @click="submitForm">确 定</el-button><el-button @click="cancel">取 消</el-button></template>');
p('    </el-dialog>');

fs.writeFileSync(f, w.join('\n'), 'utf8');
console.log('Part 1 written:', w.length, 'lines');
